import React, { useState } from 'react'; 
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery } from "@apollo/client";
import { GET_SEARCH } from '../graphql/queries';
import Card from '../components/Card/Card';
import Link from 'next/link'
import { createStore } from 'redux';
import { useSelector, useDispatch } from 'react-redux'
import { searchBussiness } from '../store/slices/businessSlice';




// const GET_ORGANIZATION = 
// gql`
//     query business {
//       business(id: "garaje-san-francisco") {
//         name
//         id
//         alias
//         rating
//         url
//       }
//     }
// `;

const _LOCATION = 'leon guanajuato';
const _LIMIT = 10;

export default function Home() {
  const { search }  = useSelector(state=> state.business);
  const dispatch = useDispatch();
  // const { loading:getOrgLoading, error, data,} = useQuery(GET_SEARCH, {
  //   variables: { term: search, location:_LOCATION, limit: _LIMIT},
  //   fetchPolicy: 'cache-and-network',
  //   // onCompleted(data){
  //   //   console.log("DATA", data)
  //   // },
  // });

  const onSearch =(event) => {
        dispatch(searchBussiness(event.target.value))
  }

  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home-container">
        <input  className='input' type="text" name="name" onChange={onSearch} />
        <button onClick={()=> dispatch(increment())}>INCREMENT</button>
        <button onClick={()=> dispatch(decrement())}>DECREMENT</button>
        <button onClick={()=> dispatch(incrementByAmount(33))}>INCREMENT BY 33</button>
        {/* <div>COUNT: {count}</div> */}
        {/* {data?.search?.business?.map((business, index)=> {
          return(
            <Card key={index} business={business} />
          )
        })} */}
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
